### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by per1234** [WickedDevice/WildFire-Arduino-Core#4]
I work on a couple of bootloader projects([avr_boot](https://github.com/zevero/avr_boot) and [Ariadne](https://github.com/per1234/Ariadne-Bootloader)) and would like to add direct support for the WildFire pinouts but I would need to use your pins_arduino.h files to do this. Any chance you could add license information to those files or the repository in general so I could see if this is possible? Thanks, Per

**Comment by vicatcu** [comment]
@per1234 yea that would be no problem at all. I could use advice. What would you recommend? I think Optiboot, which I extended for the WildFire dual boot variant is, I think, GPLv2+ fwiw. And that's carried through in the source code (e.g. [here](https://github.com/WickedDevice/WildFire-Arduino-Core/blob/master/WickedDevice/bootloaders/spiflash_optiboot/optiboot.c#L69-L87)). Should I just add the same comments to the pins_arduino.h files, or put a LICENSE.txt file in the root of the repository, or something else?

**Comment by vicatcu** [comment]
Actually better would probably be putting [this](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/variants/standard/pins_arduino.h#L1-L21) near the top of the pins_arduino.h.

**Comment by per1234** [comment]
I'm really very clueless on the license issue. I just want to make sure I'm not going to do anything that will upset anyone. I think the text you propose to add to the pins_arduino.h files is good. That's very similar to what is on the avr-developers variant: https://github.com/JChristensen/mighty-1284p/blob/v1.6.3/avr/variants/avr_developers/pins_arduino.h#L2-L20. Thanks!

**Comment by vicatcu** [comment]
Addressed by commit b1bd17036ef9a5ac3b94cf03878b2b93f44c8359. Thanks for raising this :-)
